### ISSUE TITLE
[bug/local] - No info provided on how to run E2E tests locally

### ISSUE THREAD

**Issue by matyasjay** [onebeyond/agnostic-cms-harmonizer#12]
## Description

The pre-commit hook runs both unit and e2e tests. However, it seems that the Contentful e2e config makes use of several environmental variables which are not available and there is no information provided about.

## Expected Behavior

The documentation contains all the necessary steps to run any kind of tests in local environment.

## Actual Behavior

No info, failing tests.

## Possible Fix

Not sure if the e2e tests are supposed to run against an existing test CF space or should be mocked. Depending on this, we need to add the clear instructions on how to work with the pipeline.

## Steps to Reproduce

1. `npm run test:e2e`
2. Witness error in the output

## Context

Tried to commit my changes on local machine. Worked around the issue by adding `--no-verify` flag after running the unit tests manually. This issue currently blocks the e2e verification on third-party machines.

## Your Environment

* Version used: `latest`
* Environment name and version (e.g. Chrome 39, node.js 5.4): `Node 20.10.0/npm 10.2.3`
* Operating System and version (desktop or mobile): `macOS Ventura 13.6.3 (22G436)`
* Link to your project: NA

**Comment by inigomarquinez** [comment]
Information provided in the README file :)
